### ISSUE TITLE
View Controller Showing up Empty

### ISSUE THREAD

**Issue by kyco16** [yichizhang/YZSwipeBetweenViewController#4]
```
self.swipeVC = [YZSwipeBetweenViewController new];
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    UIViewController* theController = [storyboard instantiateViewControllerWithIdentifier:@"FollowingNewsTableView"];
    UIViewController* theController2 = [storyboard instantiateViewControllerWithIdentifier:@"MeNewsTableView"];
    UINavigationController *navCon1 =
    [[UINavigationController alloc]initWithRootViewController:theController];
    UINavigationController *navCon2 =
    [[UINavigationController alloc]initWithRootViewController:theController2];    
    self.swipeVC.viewControllers = @[navCon1, navCon2];
```

This is what my view did load looks like. I have a storyboard and I have the regular view controller connected to a nav controller (embedded like any other setup). When I load the view, it show up empty and my code looks very similar to yours. If not, just typed a little differently.

**Comment by yichizhang** [comment]
Check if you've done 
	// Init the window
	self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
	self.window.backgroundColor = [UIColor blackColor];
	// Your code

	// Set swipeVC as the root view controller and make it key and visible.
	self.window.rootViewController = self. swipeVC;
	[self.window makeKeyAndVisible];

**Comment by yichizhang** [comment]
Try the latest version https://github.com/yichizhang/YZSwipeBetweenViewController/releases/tag/0.1.0
