### ISSUE TITLE
Issue with hiding status bar on child view controllers

### ISSUE THREAD

**Issue by latne1ec** [yichizhang/YZSwipeBetweenViewController#5]
First off, thanks for the great library! 

I have two child view controllers. The first is a camera view that takes up the entire screen which is where I would like to have my status bar hidden. The second VC is a TableViewController where I would like to have the status bar visible. (Much like Snapchat)

In each perspective VC class I have the status bar setting set accordingly however it seems to be overridden by the Parent VC which is the YZSwipe class. 

Any idea how I would go about implementing this?

**Comment by latne1ec** [comment]
Never mind, I figured it out!

Thanks

**Comment by yichizhang** [comment]
That's good. How did you implement it?

**Comment by latne1ec** [comment]
In the scrollViewDidEndDecelerating method I just detect the scrollView contentOffset currently displayed on the screen and hide the status bar accordingly.
