### ISSUE TITLE
YZSwipe under a Navigation Bar

### ISSUE THREAD

**Issue by micnguyen** [yichizhang/YZSwipeBetweenViewController#6]
Hi,

Thanks for the great and simple library. I've hit a situation where I have a setup where I'd like the YZSwipe underneath a NavigationController rather than each VC be in a separate NavigationController inside YZSwipe because that swipes the navigation bar and it looks ugly.

But when I do put YZSwipe inside the NavigationController, the YZSwipe goes crazy (slides below navigation, starts to scroll horizontally/vertically). Is there a way around this? 

Thanks,
Michael

**Comment by yichizhang** [comment]
Maybe you could use a UIPageViewController.

**Comment by yichizhang** [comment]
Try the latest version https://github.com/yichizhang/YZSwipeBetweenViewController/releases/tag/0.1.0
