### ISSUE TITLE
InitialViewControllerIndex doesn't work after assigning ViewControllers

### ISSUE THREAD

**Issue by micnguyen** [yichizhang/YZSwipeBetweenViewController#7]
Hi,

When settings the ViewControllers for an instance of YZSwipe, it will then set the selected VC based off the value of InitialViewControllerIndex. However, setting the index after setting the view controllers does not work and I think that's a bug because often the size of the array of viewcontrollers that you're plugging is indeterminate.

`self.swipeBetweenVc.viewControllers = @[safetyPlanIndexVc, navCon1, navCon2, navCon3];
    self.swipeBetweenVc.initialViewControllerIndex = 1;
` does set the initial index whilst

`
    self.swipeBetweenVc.initialViewControllerIndex = 1;
self.swipeBetweenVc.viewControllers = @[safetyPlanIndexVc, navCon1, navCon2, navCon3];
` does work (but is weird).

**Comment by yichizhang** [comment]
You are right, that's weird. It's not a bug though. Have a look at the source code. Feel free to send me a pull request.

**Comment by yichizhang** [comment]
Try the latest version https://github.com/yichizhang/YZSwipeBetweenViewController/releases/tag/0.1.0
